language: cpp
sudo: required
compiler: gcc
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.9
      env: CXX_COMPILER=g++-4.9
os:
  - linux
before_install:
  - test -n ${CC} && unset CC
  - test -n ${CXX} && unset CXX
  - sudo apt-get update -qq
  - sudo apt-get install -y libtbb-dev mpich2 cmake
install:
  - cmake -version
script:
  - cmake -H. -Bbuild -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DMPI_CXX_COMPILER=mpicxx -DCMAKE_BUILD_TYPE=debug 
  - cd build && make install



