language: cpp
sudo: required
matrix:
  include:
   - os: linux
     compiler: gcc
     addons:
       apt:
         sources:
         - ubuntu-toolchain-r-test
         - george-edison55-precise-backports
         packages:
         - cmake
         - cmake-data
         - g++-4.9
     env: CXX_COMPILER='g++-4.9'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libtbb-dev mpich2
install:
  - cmake -version
script:
  - cmake -H. -Bbuild -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DMPI_CXX_COMPILER=mpicxx -DCMAKE_BUILD_TYPE=debug -DCMAKE_CXX_FLAGS=-coverage
  - cd build && make install
  - ctest
after_success:
  - bash <(curl -s https://codecov.io/bash)
